# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_pointStore.ui'
#
# Created: Wed Feb 17 08:40:12 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Principal(object):
    def setupUi(self, Principal):
        Principal.setObjectName(_fromUtf8("Principal"))
        Principal.resize(1020, 760)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Principal.sizePolicy().hasHeightForWidth())
        Principal.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("pointvent-shell-system/pyventa.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Principal.setWindowIcon(icon)
        Principal.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtGui.QWidget(Principal)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.bventa = QtGui.QToolButton(self.widget)
        self.bventa.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bventa.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("images/32/add1-32.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bventa.setIcon(icon1)
        self.bventa.setIconSize(QtCore.QSize(32, 32))
        self.bventa.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.bventa.setAutoRaise(True)
        self.bventa.setObjectName(_fromUtf8("bventa"))
        self.horizontalLayout_3.addWidget(self.bventa)
        self.beliminar = QtGui.QToolButton(self.widget)
        self.beliminar.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("images/32/Delete-32.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.beliminar.setIcon(icon2)
        self.beliminar.setIconSize(QtCore.QSize(32, 32))
        self.beliminar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.beliminar.setAutoRaise(True)
        self.beliminar.setObjectName(_fromUtf8("beliminar"))
        self.horizontalLayout_3.addWidget(self.beliminar)
        self.btCerrarVenta = QtGui.QToolButton(self.widget)
        self.btCerrarVenta.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btCerrarVenta.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("images/32/Check-32.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btCerrarVenta.setIcon(icon3)
        self.btCerrarVenta.setIconSize(QtCore.QSize(32, 32))
        self.btCerrarVenta.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btCerrarVenta.setAutoRaise(True)
        self.btCerrarVenta.setObjectName(_fromUtf8("btCerrarVenta"))
        self.horizontalLayout_3.addWidget(self.btCerrarVenta)
        self.blimpiar = QtGui.QToolButton(self.widget)
        self.blimpiar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.blimpiar.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("images/32/Undo-32.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.blimpiar.setIcon(icon4)
        self.blimpiar.setIconSize(QtCore.QSize(32, 32))
        self.blimpiar.setPopupMode(QtGui.QToolButton.DelayedPopup)
        self.blimpiar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.blimpiar.setAutoRaise(True)
        self.blimpiar.setObjectName(_fromUtf8("blimpiar"))
        self.horizontalLayout_3.addWidget(self.blimpiar)
        self.bbuska = QtGui.QToolButton(self.widget)
        self.bbuska.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bbuska.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("images/32/Find-32.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bbuska.setIcon(icon5)
        self.bbuska.setIconSize(QtCore.QSize(32, 32))
        self.bbuska.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.bbuska.setAutoRaise(True)
        self.bbuska.setObjectName(_fromUtf8("bbuska"))
        self.horizontalLayout_3.addWidget(self.bbuska)
        self.badmin = QtGui.QToolButton(self.widget)
        self.badmin.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.badmin.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("images/32/User-32.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.badmin.setIcon(icon6)
        self.badmin.setIconSize(QtCore.QSize(32, 32))
        self.badmin.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.badmin.setAutoRaise(True)
        self.badmin.setObjectName(_fromUtf8("badmin"))
        self.horizontalLayout_3.addWidget(self.badmin)
        self.btCorteCaja = QtGui.QToolButton(self.widget)
        self.btCorteCaja.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btCorteCaja.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("images/32/open-32.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btCorteCaja.setIcon(icon7)
        self.btCorteCaja.setIconSize(QtCore.QSize(32, 32))
        self.btCorteCaja.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btCorteCaja.setAutoRaise(True)
        self.btCorteCaja.setObjectName(_fromUtf8("btCorteCaja"))
        self.horizontalLayout_3.addWidget(self.btCorteCaja)
        self.verticalLayout_10.addWidget(self.widget)
        self.stack = QtGui.QStackedWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stack.sizePolicy().hasHeightForWidth())
        self.stack.setSizePolicy(sizePolicy)
        self.stack.setObjectName(_fromUtf8("stack"))
        self.pageVenta = QtGui.QWidget()
        self.pageVenta.setObjectName(_fromUtf8("pageVenta"))
        self.gridLayout = QtGui.QGridLayout(self.pageVenta)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gingreso = QtGui.QGroupBox(self.pageVenta)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(200)
        sizePolicy.setHeightForWidth(self.gingreso.sizePolicy().hasHeightForWidth())
        self.gingreso.setSizePolicy(sizePolicy)
        self.gingreso.setMaximumSize(QtCore.QSize(16777215, 120))
        self.gingreso.setFlat(False)
        self.gingreso.setObjectName(_fromUtf8("gingreso"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.gingreso)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.gridLayout_2.setHorizontalSpacing(10)
        self.gridLayout_2.setVerticalSpacing(6)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.linfo2 = QtGui.QLabel(self.gingreso)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.linfo2.setFont(font)
        self.linfo2.setStyleSheet(_fromUtf8("background-color: rgb(235, 212, 35);\n"
"color: rgb(17, 65, 94);"))
        self.linfo2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.linfo2.setObjectName(_fromUtf8("linfo2"))
        self.gridLayout_2.addWidget(self.linfo2, 1, 1, 1, 1)
        self.linfo = QtGui.QLabel(self.gingreso)
        self.linfo.setStyleSheet(_fromUtf8("background-color: rgb(0, 153, 75);\n"
"color: rgb(0, 0, 0);"))
        self.linfo.setText(_fromUtf8(""))
        self.linfo.setTextFormat(QtCore.Qt.RichText)
        self.linfo.setPixmap(QtGui.QPixmap(_fromUtf8("../../.designer/backup/images/hzpyven.png")))
        self.linfo.setScaledContents(False)
        self.linfo.setAlignment(QtCore.Qt.AlignCenter)
        self.linfo.setObjectName(_fromUtf8("linfo"))
        self.gridLayout_2.addWidget(self.linfo, 1, 0, 1, 1)
        self.cant = QtGui.QLineEdit(self.gingreso)
        self.cant.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cant.setFont(font)
        self.cant.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cant.setObjectName(_fromUtf8("cant"))
        self.gridLayout_2.addWidget(self.cant, 0, 1, 1, 1)
        self.codigo = QtGui.QLineEdit(self.gingreso)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.codigo.setFont(font)
        self.codigo.setObjectName(_fromUtf8("codigo"))
        self.gridLayout_2.addWidget(self.codigo, 0, 0, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout_2)
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setContentsMargins(10, -1, 10, -1)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.lfecha = QtGui.QLabel(self.gingreso)
        self.lfecha.setTextFormat(QtCore.Qt.RichText)
        self.lfecha.setObjectName(_fromUtf8("lfecha"))
        self.verticalLayout_13.addWidget(self.lfecha)
        self.lnota = QtGui.QLabel(self.gingreso)
        self.lnota.setTextFormat(QtCore.Qt.RichText)
        self.lnota.setObjectName(_fromUtf8("lnota"))
        self.verticalLayout_13.addWidget(self.lnota)
        self.horizontalLayout_5.addLayout(self.verticalLayout_13)
        self.widget_2 = QtGui.QWidget(self.gingreso)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.widget_2)
        self.verticalLayout_8.setMargin(0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.rticket = QtGui.QRadioButton(self.widget_2)
        self.rticket.setChecked(True)
        self.rticket.setObjectName(_fromUtf8("rticket"))
        self.verticalLayout_8.addWidget(self.rticket)
        self.rpresup = QtGui.QRadioButton(self.widget_2)
        self.rpresup.setObjectName(_fromUtf8("rpresup"))
        self.verticalLayout_8.addWidget(self.rpresup)
        self.horizontalLayout_5.addWidget(self.widget_2)
        self.widget_3 = QtGui.QWidget(self.gingreso)
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.widget_3)
        self.verticalLayout_11.setMargin(0)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.rmen = QtGui.QRadioButton(self.widget_3)
        self.rmen.setChecked(True)
        self.rmen.setObjectName(_fromUtf8("rmen"))
        self.verticalLayout_11.addWidget(self.rmen)
        self.rmay = QtGui.QRadioButton(self.widget_3)
        self.rmay.setObjectName(_fromUtf8("rmay"))
        self.verticalLayout_11.addWidget(self.rmay)
        self.rtemp = QtGui.QRadioButton(self.widget_3)
        self.rtemp.setObjectName(_fromUtf8("rtemp"))
        self.verticalLayout_11.addWidget(self.rtemp)
        self.horizontalLayout_5.addWidget(self.widget_3)
        self.ltotal = QtGui.QLabel(self.gingreso)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.ltotal.setFont(font)
        self.ltotal.setScaledContents(True)
        self.ltotal.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ltotal.setMargin(5)
        self.ltotal.setObjectName(_fromUtf8("ltotal"))
        self.horizontalLayout_5.addWidget(self.ltotal)
        self.verticalLayout_2.addWidget(self.gingreso)
        self.splitter = QtGui.QSplitter(self.pageVenta)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.lista2 = QtGui.QListWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lista2.sizePolicy().hasHeightForWidth())
        self.lista2.setSizePolicy(sizePolicy)
        self.lista2.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lista2.setFont(font)
        self.lista2.setStyleSheet(_fromUtf8(""))
        self.lista2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lista2.setFrameShadow(QtGui.QFrame.Sunken)
        self.lista2.setSpacing(2)
        self.lista2.setViewMode(QtGui.QListView.ListMode)
        self.lista2.setWordWrap(True)
        self.lista2.setObjectName(_fromUtf8("lista2"))
        item = QtGui.QListWidgetItem()
        self.lista2.addItem(item)
        self.verticalLayoutWidget = QtGui.QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_9.setMargin(0)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.gcanasta = QtGui.QGroupBox(self.verticalLayoutWidget)
        self.gcanasta.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(212, 210, 241, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.gcanasta.setFlat(True)
        self.gcanasta.setObjectName(_fromUtf8("gcanasta"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.gcanasta)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.tabla = QtGui.QTableWidget(self.gcanasta)
        self.tabla.setStyleSheet(_fromUtf8("color: rgb(73, 73, 73);\n"
"alternate-background-color: rgb(102, 171, 255);"))
        self.tabla.setFrameShadow(QtGui.QFrame.Raised)
        self.tabla.setAlternatingRowColors(True)
        self.tabla.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tabla.setGridStyle(QtCore.Qt.DotLine)
        self.tabla.setObjectName(_fromUtf8("tabla"))
        self.tabla.setColumnCount(5)
        self.tabla.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tabla.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tabla.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tabla.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tabla.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tabla.setHorizontalHeaderItem(4, item)
        self.verticalLayout_12.addWidget(self.tabla)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_26 = QtGui.QLabel(self.gcanasta)
        self.label_26.setMinimumSize(QtCore.QSize(300, 0))
        self.label_26.setMaximumSize(QtCore.QSize(300, 219))
        self.label_26.setText(_fromUtf8(""))
        self.label_26.setPixmap(QtGui.QPixmap(_fromUtf8("images/hzpyven.png")))
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_4.addWidget(self.label_26)
        self.datos = QtGui.QTextBrowser(self.gcanasta)
        self.datos.setMaximumSize(QtCore.QSize(16777215, 70))
        self.datos.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(42, 138, 255, 255), stop:1 rgba(96, 178, 255, 255));"))
        self.datos.setFrameShadow(QtGui.QFrame.Sunken)
        self.datos.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.datos.setDocumentTitle(_fromUtf8(""))
        self.datos.setObjectName(_fromUtf8("datos"))
        self.horizontalLayout_4.addWidget(self.datos)
        self.verticalLayout_12.addLayout(self.horizontalLayout_4)
        self.verticalLayout_9.addWidget(self.gcanasta)
        self.verticalLayout_2.addWidget(self.splitter)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 2)
        self.stack.addWidget(self.pageVenta)
        self.pageBuscador = QtGui.QWidget()
        self.pageBuscador.setObjectName(_fromUtf8("pageBuscador"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.pageBuscador)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(8)
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_12 = QtGui.QLabel(self.pageBuscador)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_2.addWidget(self.label_12)
        self.ttext = QtGui.QLineEdit(self.pageBuscador)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.ttext.setFont(font)
        self.ttext.setObjectName(_fromUtf8("ttext"))
        self.horizontalLayout_2.addWidget(self.ttext)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(18)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.rprod = QtGui.QRadioButton(self.pageBuscador)
        self.rprod.setChecked(True)
        self.rprod.setObjectName(_fromUtf8("rprod"))
        self.horizontalLayout.addWidget(self.rprod)
        self.rlam = QtGui.QRadioButton(self.pageBuscador)
        self.rlam.setObjectName(_fromUtf8("rlam"))
        self.horizontalLayout.addWidget(self.rlam)
        self.rbio = QtGui.QRadioButton(self.pageBuscador)
        self.rbio.setObjectName(_fromUtf8("rbio"))
        self.horizontalLayout.addWidget(self.rbio)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.tbusk = QtGui.QTableWidget(self.pageBuscador)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.tbusk.setFont(font)
        self.tbusk.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tbusk.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tbusk.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tbusk.setGridStyle(QtCore.Qt.DashLine)
        self.tbusk.setObjectName(_fromUtf8("tbusk"))
        self.tbusk.setColumnCount(0)
        self.tbusk.setRowCount(0)
        self.verticalLayout_3.addWidget(self.tbusk)
        self.stack.addWidget(self.pageBuscador)
        self.pageAdmin = QtGui.QWidget()
        self.pageAdmin.setObjectName(_fromUtf8("pageAdmin"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.pageAdmin)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_2 = QtGui.QLabel(self.pageAdmin)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_5.addWidget(self.label_2)
        self.tabWidget = QtGui.QTabWidget(self.pageAdmin)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_4 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_4.addWidget(self.label_4)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_5)
        self.tpcodigo = QtGui.QLineEdit(self.tab)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tpcodigo.setFont(font)
        self.tpcodigo.setObjectName(_fromUtf8("tpcodigo"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.tpcodigo)
        self.bpgenera = QtGui.QPushButton(self.tab)
        self.bpgenera.setObjectName(_fromUtf8("bpgenera"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.bpgenera)
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_6)
        self.tpdesc = QtGui.QLineEdit(self.tab)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tpdesc.setFont(font)
        self.tpdesc.setObjectName(_fromUtf8("tpdesc"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.tpdesc)
        self.label_7 = QtGui.QLabel(self.tab)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_7)
        self.cpdep = QtGui.QComboBox(self.tab)
        self.cpdep.setObjectName(_fromUtf8("cpdep"))
        self.cpdep.addItem(_fromUtf8(""))
        self.cpdep.addItem(_fromUtf8(""))
        self.cpdep.addItem(_fromUtf8(""))
        self.cpdep.addItem(_fromUtf8(""))
        self.cpdep.addItem(_fromUtf8(""))
        self.cpdep.addItem(_fromUtf8(""))
        self.cpdep.addItem(_fromUtf8(""))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.cpdep)
        self.label_8 = QtGui.QLabel(self.tab)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_8)
        self.txtPrecio = QtGui.QLineEdit(self.tab)
        self.txtPrecio.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txtPrecio.setFont(font)
        self.txtPrecio.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtPrecio.setObjectName(_fromUtf8("txtPrecio"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.txtPrecio)
        self.label_10 = QtGui.QLabel(self.tab)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_10)
        self.txtPrecioPublico = QtGui.QLineEdit(self.tab)
        self.txtPrecioPublico.setMaximumSize(QtCore.QSize(121, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.txtPrecioPublico.setFont(font)
        self.txtPrecioPublico.setStyleSheet(_fromUtf8("color: rgb(255, 103, 53);"))
        self.txtPrecioPublico.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtPrecioPublico.setObjectName(_fromUtf8("txtPrecioPublico"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.txtPrecioPublico)
        self.bpagregar = QtGui.QPushButton(self.tab)
        self.bpagregar.setMinimumSize(QtCore.QSize(0, 50))
        self.bpagregar.setObjectName(_fromUtf8("bpagregar"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.bpagregar)
        self.verticalLayout_4.addLayout(self.formLayout)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8("images/16/add2-16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab, icon8, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_6.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_3 = QtGui.QLabel(self.tab_2)
        self.label_3.setTextFormat(QtCore.Qt.PlainText)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_6.addWidget(self.label_3)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, 6, -1, -1)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_13 = QtGui.QLabel(self.tab_2)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_6.addWidget(self.label_13)
        self.tfiltro = QtGui.QLineEdit(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.tfiltro.setFont(font)
        self.tfiltro.setObjectName(_fromUtf8("tfiltro"))
        self.horizontalLayout_6.addWidget(self.tfiltro)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.tplista = QtGui.QTableWidget(self.tab_2)
        self.tplista.setAutoScrollMargin(20)
        self.tplista.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tplista.setAlternatingRowColors(True)
        self.tplista.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tplista.setGridStyle(QtCore.Qt.DashLine)
        self.tplista.setWordWrap(False)
        self.tplista.setObjectName(_fromUtf8("tplista"))
        self.tplista.setColumnCount(6)
        self.tplista.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tplista.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tplista.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tplista.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tplista.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tplista.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tplista.setHorizontalHeaderItem(5, item)
        self.verticalLayout_6.addWidget(self.tplista)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8("images/32/edit32.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_2, icon9, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.txtFilterLam = QtGui.QLineEdit(self.tab_4)
        self.txtFilterLam.setGeometry(QtCore.QRect(170, 80, 491, 33))
        self.txtFilterLam.setObjectName(_fromUtf8("txtFilterLam"))
        self.tbLaminas = QtGui.QTableWidget(self.tab_4)
        self.tbLaminas.setGeometry(QtCore.QRect(20, 130, 641, 381))
        self.tbLaminas.setObjectName(_fromUtf8("tbLaminas"))
        self.tbLaminas.setColumnCount(2)
        self.tbLaminas.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tbLaminas.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tbLaminas.setHorizontalHeaderItem(1, item)
        self.label_28 = QtGui.QLabel(self.tab_4)
        self.label_28.setGeometry(QtCore.QRect(20, 90, 121, 21))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.label_29 = QtGui.QLabel(self.tab_4)
        self.label_29.setGeometry(QtCore.QRect(20, 30, 591, 21))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.tab_4)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(690, 80, 271, 131))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_15.setMargin(0)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_30 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.horizontalLayout_11.addWidget(self.label_30)
        self.txtTituloLam = QtGui.QLineEdit(self.verticalLayoutWidget_3)
        self.txtTituloLam.setObjectName(_fromUtf8("txtTituloLam"))
        self.horizontalLayout_11.addWidget(self.txtTituloLam)
        self.verticalLayout_15.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_31 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.horizontalLayout_10.addWidget(self.label_31)
        self.txtCodigoLam = QtGui.QLineEdit(self.verticalLayoutWidget_3)
        self.txtCodigoLam.setObjectName(_fromUtf8("txtCodigoLam"))
        self.horizontalLayout_10.addWidget(self.txtCodigoLam)
        self.verticalLayout_15.addLayout(self.horizontalLayout_10)
        self.btNuevaLam = QtGui.QPushButton(self.verticalLayoutWidget_3)
        self.btNuevaLam.setObjectName(_fromUtf8("btNuevaLam"))
        self.verticalLayout_15.addWidget(self.btNuevaLam)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.verticalLayout_5.addWidget(self.tabWidget)
        self.stack.addWidget(self.pageAdmin)
        self.pageCaja = QtGui.QWidget()
        self.pageCaja.setObjectName(_fromUtf8("pageCaja"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.pageCaja)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, -1, 0, 0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.rDia = QtGui.QRadioButton(self.pageCaja)
        self.rDia.setEnabled(True)
        self.rDia.setChecked(True)
        self.rDia.setAutoRepeat(False)
        self.rDia.setAutoExclusive(True)
        self.rDia.setObjectName(_fromUtf8("rDia"))
        self.horizontalLayout_8.addWidget(self.rDia)
        self.rPeriodo = QtGui.QRadioButton(self.pageCaja)
        self.rPeriodo.setObjectName(_fromUtf8("rPeriodo"))
        self.horizontalLayout_8.addWidget(self.rPeriodo)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.txtPeriodo = QtGui.QLabel(self.pageCaja)
        self.txtPeriodo.setTextFormat(QtCore.Qt.AutoText)
        self.txtPeriodo.setObjectName(_fromUtf8("txtPeriodo"))
        self.verticalLayout.addWidget(self.txtPeriodo)
        self.calendario = QtGui.QCalendarWidget(self.pageCaja)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calendario.sizePolicy().hasHeightForWidth())
        self.calendario.setSizePolicy(sizePolicy)
        self.calendario.setObjectName(_fromUtf8("calendario"))
        self.verticalLayout.addWidget(self.calendario)
        self.lbTotalVendido = QtGui.QLabel(self.pageCaja)
        self.lbTotalVendido.setObjectName(_fromUtf8("lbTotalVendido"))
        self.verticalLayout.addWidget(self.lbTotalVendido)
        self.lbTotalGanancia = QtGui.QLabel(self.pageCaja)
        self.lbTotalGanancia.setObjectName(_fromUtf8("lbTotalGanancia"))
        self.verticalLayout.addWidget(self.lbTotalGanancia)
        self.horizontalLayout_7.addLayout(self.verticalLayout)
        self.tbNotas = QtGui.QTableWidget(self.pageCaja)
        self.tbNotas.setObjectName(_fromUtf8("tbNotas"))
        self.tbNotas.setColumnCount(0)
        self.tbNotas.setRowCount(0)
        self.horizontalLayout_7.addWidget(self.tbNotas)
        self.stack.addWidget(self.pageCaja)
        self.verticalLayout_10.addWidget(self.stack)
        Principal.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(Principal)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1020, 25))
        self.menubar.setStyleSheet(_fromUtf8(""))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuNota = QtGui.QMenu(self.menubar)
        self.menuNota.setObjectName(_fromUtf8("menuNota"))
        self.menuClientes = QtGui.QMenu(self.menubar)
        self.menuClientes.setObjectName(_fromUtf8("menuClientes"))
        self.menuConfiguraciones = QtGui.QMenu(self.menubar)
        self.menuConfiguraciones.setObjectName(_fromUtf8("menuConfiguraciones"))
        self.menuAyuda = QtGui.QMenu(self.menubar)
        self.menuAyuda.setObjectName(_fromUtf8("menuAyuda"))
        self.menuVentana = QtGui.QMenu(self.menubar)
        self.menuVentana.setObjectName(_fromUtf8("menuVentana"))
        Principal.setMenuBar(self.menubar)
        self.actionNueva = QtGui.QAction(Principal)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8("images/16/document_16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNueva.setIcon(icon10)
        self.actionNueva.setObjectName(_fromUtf8("actionNueva"))
        self.actionImprimir = QtGui.QAction(Principal)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8("images/16/print_16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionImprimir.setIcon(icon11)
        self.actionImprimir.setObjectName(_fromUtf8("actionImprimir"))
        self.actionEliminar = QtGui.QAction(Principal)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8("../../.designer/backup/images/icons/elimina.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEliminar.setIcon(icon12)
        self.actionEliminar.setObjectName(_fromUtf8("actionEliminar"))
        self.actionBuscador = QtGui.QAction(Principal)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8("../../.designer/backup/images/icons/buscador.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBuscador.setIcon(icon13)
        self.actionBuscador.setObjectName(_fromUtf8("actionBuscador"))
        self.actionAdministrador = QtGui.QAction(Principal)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8("../../.designer/backup/images/icons/16/plus.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAdministrador.setIcon(icon14)
        self.actionAdministrador.setObjectName(_fromUtf8("actionAdministrador"))
        self.actionVentas_del_dia = QtGui.QAction(Principal)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8("../../.designer/backup/images/icons/16/phonebook.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionVentas_del_dia.setIcon(icon15)
        self.actionVentas_del_dia.setObjectName(_fromUtf8("actionVentas_del_dia"))
        self.actionCorte = QtGui.QAction(Principal)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8("images/16/right_16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCorte.setIcon(icon16)
        self.actionCorte.setObjectName(_fromUtf8("actionCorte"))
        self.actionEditar_nota = QtGui.QAction(Principal)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8("images/16/folder_16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEditar_nota.setIcon(icon17)
        self.actionEditar_nota.setObjectName(_fromUtf8("actionEditar_nota"))
        self.actionAgregar_clientes = QtGui.QAction(Principal)
        self.actionAgregar_clientes.setObjectName(_fromUtf8("actionAgregar_clientes"))
        self.actionCartera_de_clientes = QtGui.QAction(Principal)
        self.actionCartera_de_clientes.setObjectName(_fromUtf8("actionCartera_de_clientes"))
        self.action_Cambiar_cliente_actual = QtGui.QAction(Principal)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(_fromUtf8("../../.designer/backup/images/icons/camuser.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Cambiar_cliente_actual.setIcon(icon18)
        self.action_Cambiar_cliente_actual.setObjectName(_fromUtf8("action_Cambiar_cliente_actual"))
        self.actionBase_de_datos = QtGui.QAction(Principal)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(_fromUtf8("../../.designer/backup/images/icons/16/building.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBase_de_datos.setIcon(icon19)
        self.actionBase_de_datos.setObjectName(_fromUtf8("actionBase_de_datos"))
        self.actionUsuarios = QtGui.QAction(Principal)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(_fromUtf8("../../.designer/backup/images/icons/16/people.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUsuarios.setIcon(icon20)
        self.actionUsuarios.setObjectName(_fromUtf8("actionUsuarios"))
        self.actionUpdate = QtGui.QAction(Principal)
        self.actionUpdate.setObjectName(_fromUtf8("actionUpdate"))
        self.actionCompleta = QtGui.QAction(Principal)
        self.actionCompleta.setObjectName(_fromUtf8("actionCompleta"))
        self.actionNormal = QtGui.QAction(Principal)
        self.actionNormal.setObjectName(_fromUtf8("actionNormal"))
        self.actionMini = QtGui.QAction(Principal)
        self.actionMini.setObjectName(_fromUtf8("actionMini"))
        self.actionPlantilla_de_presupuesto = QtGui.QAction(Principal)
        self.actionPlantilla_de_presupuesto.setObjectName(_fromUtf8("actionPlantilla_de_presupuesto"))
        self.actionNota_de_venta = QtGui.QAction(Principal)
        self.actionNota_de_venta.setObjectName(_fromUtf8("actionNota_de_venta"))
        self.actionA_Pyventa = QtGui.QAction(Principal)
        self.actionA_Pyventa.setObjectName(_fromUtf8("actionA_Pyventa"))
        self.actionVersion = QtGui.QAction(Principal)
        self.actionVersion.setObjectName(_fromUtf8("actionVersion"))
        self.actionGuardar = QtGui.QAction(Principal)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(_fromUtf8("images/16/save_16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGuardar.setIcon(icon21)
        self.actionGuardar.setObjectName(_fromUtf8("actionGuardar"))
        self.actionCerrar = QtGui.QAction(Principal)
        self.actionCerrar.setObjectName(_fromUtf8("actionCerrar"))
        self.actionAcerca = QtGui.QAction(Principal)
        self.actionAcerca.setObjectName(_fromUtf8("actionAcerca"))
        self.menuNota.addAction(self.actionNueva)
        self.menuNota.addAction(self.actionEditar_nota)
        self.menuNota.addAction(self.actionGuardar)
        self.menuNota.addSeparator()
        self.menuNota.addAction(self.actionVentas_del_dia)
        self.menuNota.addAction(self.actionCorte)
        self.menuNota.addSeparator()
        self.menuNota.addAction(self.actionCerrar)
        self.menuClientes.addAction(self.actionBuscador)
        self.menuClientes.addAction(self.actionAdministrador)
        self.menuConfiguraciones.addAction(self.actionBase_de_datos)
        self.menuConfiguraciones.addAction(self.actionUsuarios)
        self.menuConfiguraciones.addAction(self.actionUpdate)
        self.menuAyuda.addAction(self.actionAcerca)
        self.menuVentana.addAction(self.actionMini)
        self.menuVentana.addAction(self.actionNormal)
        self.menuVentana.addAction(self.actionCompleta)
        self.menubar.addAction(self.menuNota.menuAction())
        self.menubar.addAction(self.menuClientes.menuAction())
        self.menubar.addAction(self.menuConfiguraciones.menuAction())
        self.menubar.addAction(self.menuVentana.menuAction())
        self.menubar.addAction(self.menuAyuda.menuAction())

        self.retranslateUi(Principal)
        self.stack.setCurrentIndex(3)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionNormal, QtCore.SIGNAL(_fromUtf8("triggered()")), Principal.showMaximized)
        QtCore.QObject.connect(self.actionCompleta, QtCore.SIGNAL(_fromUtf8("triggered()")), Principal.showFullScreen)
        QtCore.QObject.connect(self.actionCerrar, QtCore.SIGNAL(_fromUtf8("triggered()")), Principal.close)
        QtCore.QMetaObject.connectSlotsByName(Principal)
        Principal.setTabOrder(self.btCorteCaja, self.codigo)
        Principal.setTabOrder(self.codigo, self.cant)
        Principal.setTabOrder(self.cant, self.rprod)
        Principal.setTabOrder(self.rprod, self.rlam)
        Principal.setTabOrder(self.rlam, self.rbio)
        Principal.setTabOrder(self.rbio, self.tbusk)
        Principal.setTabOrder(self.tbusk, self.tabWidget)
        Principal.setTabOrder(self.tabWidget, self.tpcodigo)
        Principal.setTabOrder(self.tpcodigo, self.tpdesc)
        Principal.setTabOrder(self.tpdesc, self.cpdep)
        Principal.setTabOrder(self.cpdep, self.txtPrecio)
        Principal.setTabOrder(self.txtPrecio, self.txtPrecioPublico)
        Principal.setTabOrder(self.txtPrecioPublico, self.bpagregar)
        Principal.setTabOrder(self.bpagregar, self.bpgenera)
        Principal.setTabOrder(self.bpgenera, self.tplista)
        Principal.setTabOrder(self.tplista, self.tfiltro)

    def retranslateUi(self, Principal):
        Principal.setWindowTitle(_translate("Principal", "Pyventa - Punto de venta", None))
        self.bventa.setText(_translate("Principal", "Nota de Venta", None))
        self.bventa.setShortcut(_translate("Principal", "F2", None))
        self.beliminar.setText(_translate("Principal", "Eliminar producto", None))
        self.beliminar.setShortcut(_translate("Principal", "Del", None))
        self.btCerrarVenta.setText(_translate("Principal", "Cerrar Venta", None))
        self.btCerrarVenta.setShortcut(_translate("Principal", "F5", None))
        self.blimpiar.setText(_translate("Principal", "Limpiar todo", None))
        self.blimpiar.setShortcut(_translate("Principal", "Ctrl+N", None))
        self.bbuska.setText(_translate("Principal", "Buscador", None))
        self.bbuska.setShortcut(_translate("Principal", "F3", None))
        self.badmin.setToolTip(_translate("Principal", "F6", None))
        self.badmin.setText(_translate("Principal", "Administrador", None))
        self.badmin.setShortcut(_translate("Principal", "F6", None))
        self.btCorteCaja.setText(_translate("Principal", "Corte de caja", None))
        self.btCorteCaja.setShortcut(_translate("Principal", "Ctrl+A", None))
        self.linfo2.setText(_translate("Principal", "$00.00", None))
        self.linfo.setToolTip(_translate("Principal", "PyVenta version 2.0", None))
        self.cant.setText(_translate("Principal", "1.00", None))
        self.lfecha.setText(_translate("Principal", "<b>Fecha:</b>", None))
        self.lnota.setText(_translate("Principal", "Nota:", None))
        self.rticket.setText(_translate("Principal", "Ticket", None))
        self.rpresup.setText(_translate("Principal", "Presupuesto", None))
        self.rmen.setText(_translate("Principal", "Venta normal", None))
        self.rmay.setText(_translate("Principal", "Mayoreo", None))
        self.rtemp.setText(_translate("Principal", "Lista escolar", None))
        self.ltotal.setText(_translate("Principal", "$000.00", None))
        __sortingEnabled = self.lista2.isSortingEnabled()
        self.lista2.setSortingEnabled(False)
        item = self.lista2.item(0)
        item.setText(_translate("Principal", "Productos sugeridos", None))
        self.lista2.setSortingEnabled(__sortingEnabled)
        self.gcanasta.setTitle(_translate("Principal", "Canasta de Productos", None))
        item = self.tabla.horizontalHeaderItem(0)
        item.setText(_translate("Principal", "ref", None))
        item = self.tabla.horizontalHeaderItem(1)
        item.setText(_translate("Principal", "cant", None))
        item = self.tabla.horizontalHeaderItem(2)
        item.setText(_translate("Principal", "desc", None))
        item = self.tabla.horizontalHeaderItem(3)
        item.setText(_translate("Principal", "precio", None))
        item = self.tabla.horizontalHeaderItem(4)
        item.setText(_translate("Principal", "importe", None))
        self.datos.setHtml(_translate("Principal", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'DejaVu Sans\';\">Subtotal:         </span><span style=\" font-family:\'DejaVu Sans\'; font-weight:600;\">$ 000.00 </span></p>\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'DejaVu Sans\';\">Descuento:     </span><span style=\" font-family:\'DejaVu Sans\'; font-weight:600;\">$ 000.00</span></p>\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'DejaVu Sans\';\">Total:         </span><span style=\" font-family:\'DejaVu Sans\'; font-weight:600;\">$ 000.00</span></p></body></html>", None))
        self.label_12.setText(_translate("Principal", "Texto a buscar:", None))
        self.rprod.setText(_translate("Principal", "Productos", None))
        self.rlam.setText(_translate("Principal", "Laminas", None))
        self.rbio.setText(_translate("Principal", "Biografias", None))
        self.label_2.setText(_translate("Principal", "Administrador de productos", None))
        self.label_4.setText(_translate("Principal", "Alta de productos", None))
        self.label_5.setText(_translate("Principal", "Codigo de barras", None))
        self.bpgenera.setText(_translate("Principal", "Generar codigo", None))
        self.label_6.setText(_translate("Principal", "Descripcion del producto", None))
        self.label_7.setText(_translate("Principal", "Departamento", None))
        self.cpdep.setItemText(0, _translate("Principal", "Abarrotes", None))
        self.cpdep.setItemText(1, _translate("Principal", "Papeleria", None))
        self.cpdep.setItemText(2, _translate("Principal", "Merceria", None))
        self.cpdep.setItemText(3, _translate("Principal", "Computo", None))
        self.cpdep.setItemText(4, _translate("Principal", "Regalos", None))
        self.cpdep.setItemText(5, _translate("Principal", "Oficina", None))
        self.cpdep.setItemText(6, _translate("Principal", "Servicios", None))
        self.label_8.setText(_translate("Principal", "Costo de compra con IVA", None))
        self.label_10.setText(_translate("Principal", "Precio al publico", None))
        self.bpagregar.setText(_translate("Principal", "Agregar producto", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Principal", "Nuevo producto", None))
        self.label_3.setText(_translate("Principal", "Puedes editar directamente los datos presentados en la tabla haciendo doble click sobre el producto,\n"
"las modificaciones realizadas tendran efecto en la base de datos. ", None))
        self.label_13.setText(_translate("Principal", "Criterios de busqueda: ", None))
        self.tfiltro.setToolTip(_translate("Principal", "Escribe la descripcion del producto que buscas para poder modificarlo.", None))
        item = self.tplista.horizontalHeaderItem(0)
        item.setText(_translate("Principal", "Codigo de barras", None))
        item = self.tplista.horizontalHeaderItem(1)
        item.setText(_translate("Principal", "Referencia", None))
        item = self.tplista.horizontalHeaderItem(2)
        item.setText(_translate("Principal", "Descripcion del producto", None))
        item = self.tplista.horizontalHeaderItem(3)
        item.setText(_translate("Principal", "Departamento", None))
        item = self.tplista.horizontalHeaderItem(4)
        item.setText(_translate("Principal", "Precio", None))
        item = self.tplista.horizontalHeaderItem(5)
        item.setText(_translate("Principal", "Precio publico", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Principal", "Lista de productos", None))
        item = self.tbLaminas.horizontalHeaderItem(0)
        item.setText(_translate("Principal", "Codigo", None))
        item = self.tbLaminas.horizontalHeaderItem(1)
        item.setText(_translate("Principal", "Nombre", None))
        self.label_28.setText(_translate("Principal", "Buscar Lamina", None))
        self.label_29.setText(_translate("Principal", "Puede editar el nombre de la lamina o eliminarla en el caso de cambiar el numero ", None))
        self.label_30.setText(_translate("Principal", "Titulo  ", None))
        self.label_31.setText(_translate("Principal", "Codigo", None))
        self.btNuevaLam.setText(_translate("Principal", "Agregar nueva lamina", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Principal", "Lista laminas", None))
        self.rDia.setText(_translate("Principal", "Seleccionar Dia", None))
        self.rPeriodo.setText(_translate("Principal", "Seleccionar Periodo", None))
        self.txtPeriodo.setText(_translate("Principal", "Periodo", None))
        self.lbTotalVendido.setText(_translate("Principal", "<h2>Total vendido<h2>", None))
        self.lbTotalGanancia.setText(_translate("Principal", "<h2>Total ganancia<h2>", None))
        self.menuNota.setTitle(_translate("Principal", "Archivo", None))
        self.menuClientes.setTitle(_translate("Principal", "Herramientas", None))
        self.menuConfiguraciones.setTitle(_translate("Principal", "Configuraciones", None))
        self.menuAyuda.setTitle(_translate("Principal", "Ayuda", None))
        self.menuVentana.setTitle(_translate("Principal", "Ventana", None))
        self.actionNueva.setText(_translate("Principal", "Nueva nota", None))
        self.actionImprimir.setText(_translate("Principal", "Imprimir ", None))
        self.actionEliminar.setText(_translate("Principal", "Eliminar nota", None))
        self.actionBuscador.setText(_translate("Principal", "Buscador", None))
        self.actionAdministrador.setText(_translate("Principal", "Administrador", None))
        self.actionVentas_del_dia.setText(_translate("Principal", "Reporte de ventas", None))
        self.actionCorte.setText(_translate("Principal", "Corte del dia.", None))
        self.actionEditar_nota.setText(_translate("Principal", "Abrir nota", None))
        self.actionAgregar_clientes.setText(_translate("Principal", "Alta de clientes.", None))
        self.actionCartera_de_clientes.setText(_translate("Principal", "Cartera de clientes.", None))
        self.action_Cambiar_cliente_actual.setText(_translate("Principal", " Cambiar cliente actual", None))
        self.actionBase_de_datos.setText(_translate("Principal", "Base de datos", None))
        self.actionUsuarios.setText(_translate("Principal", "Usuarios", None))
        self.actionUpdate.setText(_translate("Principal", "Actualizacion", None))
        self.actionCompleta.setText(_translate("Principal", "Pantalla Completa", None))
        self.actionCompleta.setShortcut(_translate("Principal", "F11", None))
        self.actionNormal.setText(_translate("Principal", "Normal", None))
        self.actionNormal.setShortcut(_translate("Principal", "F10", None))
        self.actionMini.setText(_translate("Principal", "Mini", None))
        self.actionPlantilla_de_presupuesto.setText(_translate("Principal", "Plantilla de presupuesto", None))
        self.actionNota_de_venta.setText(_translate("Principal", "Nota de venta", None))
        self.actionA_Pyventa.setText(_translate("Principal", "Acerca de Point Store", None))
        self.actionVersion.setText(_translate("Principal", "Acerca de Ottarw", None))
        self.actionGuardar.setText(_translate("Principal", "Guardar", None))
        self.actionCerrar.setText(_translate("Principal", "Cerrar PointStore", None))
        self.actionCerrar.setToolTip(_translate("Principal", "Cierra el programa.", None))
        self.actionAcerca.setText(_translate("Principal", "Acerca", None))

